### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by Mran** [BigglesZX/django-admin-thumbnails#1]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\94900\AppData\Local\Temp\pip-install-yzwfp67_\django-admin-thumbnails\setup.py", line 41, in <module>
        long_description=open('README.md').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 768: illegal multibyte sequence

**Comment by BigglesZX** [comment]
@Mran Looking into this now

**Comment by BigglesZX** [comment]
@Mran Just published a new version, let me know if it resolves the issue for you. FYI I think this was caused by incorrect encoding detection of Unicode characters in the README.

**Comment by Mran** [comment]
thanks！it is  worked

**Comment by BigglesZX** [comment]
@Mran Great! 🚀
